version: "3.7"

services:
  web:
    container_name: web
    # env_file: ./.env
    build: ./backend/.
    volumes:
      - ./backend/:/backend/
      - static_volume:/backend/static # <-- bind the static volume
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 backend.wsgi:application
    networks:
      - backend_network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DJANGO_SETTINGS_MODULE=backend.settings

  backend-server:
    container_name: nginx-back
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    volumes:
      - static_volume:/backend/static # <-- bind the static volume
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - web
    tty: true

  celery:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    # entrypoint: "/bin/sh ./run-celery.sh"   # 이게 뭘까
    command: "celery -A backend worker --loglevel=info"
    depends_on:
      - web
      - rabbitmq
    tty: true

networks:
  backend_network:
    driver: bridge
volumes:
  static_volume: